### ISSUE TITLE
Not working with newest version of cloud-init

### ISSUE THREAD

**Issue by PlethoraOfHate** [LordGaav/proxmox-deploy#15]
I have not yet been able to ascertain why, but on the any version of cloud-init 0.7.7 or newer, it no longer accepts the network configuration and instead sets the VM to DHCP every time. The original release of Ubuntu 16.04 works (Ether by editing the img to remove the serial console or by using the serial patch from the repo), but as soon as you update the VM in any way (apt-get upgrade), and reboot, networking stops working.

**Comment by LordGaav** [comment]
cloud-init has been a pain in the ass since the beginning. It's way more useful on platforms like OpenStack, but not really on Proxmox. The 'NoCloud' approach I have taken doesn't seem to play nice when the VM is rebooted, as it seems to miss the options on the configuration disk.

I just deinstall cloud-init when the VM has been provisioned.
