### ISSUE TITLE
Networking VLAN and Bridge selection

### ISSUE THREAD

**Issue by zzenoxx** [LordGaav/proxmox-deploy#17]
I found traces of leaving the Vlan id empty. 
As we dont use this in our production environment how could this be done? The default value is 1 off course.

Is there a possibility to choose the vmbr on wich the kvm can connect? As we have multiple vmbr's in our environment with each a specific task.

Its a great project and works like a charm, props.

**Comment by zzenoxx** [comment]
Configure networking [Yes]:
VLAN ID [1]: empty
Please enter a valid integer between 1 and 4096.
VLAN ID [1]: None
Please enter a valid integer between 1 and 4096.
VLAN ID [1]: 'empty'
Please enter a valid integer between 1 and 4096.
VLAN ID [1]: None
Please enter a valid integer between 1 and 4096.
VLAN ID [1]: 'None'
Please enter a valid integer between 1 and 4096.
VLAN ID [1]: empty
Please enter a valid integer between 1 and 4096.
VLAN ID [1]: null
Please enter a valid integer between 1 and 4096.
VLAN ID [1]: 'null'
Please enter a valid integer between 1 and 4096.
VLAN ID [1]:

**Comment by PlethoraOfHate** [comment]
I have a wildly "different" version of this app that includes ceph support, as well as the VLAN/vmbr feature you mention. Problem is, I also heavliy modified it to support passing in an ini file instead of command line params so I could use it with ansible, with the eventual goal of turning it into a native ansible plugin. Sadly, I haven't been able to mess with it in quite a while. I create a branch and then push my changes there. I doubt it will get meged since I changed the functionality so drastically

**Comment by PlethoraOfHate** [comment]
Uploaded my version here. https://github.com/PlethoraOfHate/proxmox-deploy
Will try to get docs written at some point. My apologies, it's been a looooong time since I worked on this

**Comment by LordGaav** [comment]
@zzenoxx : providing 'empty' as value should work (or 'None' or 'null')

```
Configure networking [Yes]: 
VLAN ID (Specify a value, or 'empty') [1]: empty
```

Could you have been using a very old version? Please try again with the latest version.

**Comment by LordGaav** [comment]
Actually, it seems like I added it after version 0.3, which is the latest version on PyPi. I have uploaded version 0.4.0, please try again with that version.
