### ISSUE TITLE
Still Being Maintained?

### ISSUE THREAD

**Issue by bcleonard** [LordGaav/proxmox-deploy#18]
Is this project still being maintained?

I have a fix that I need for my environment (need to increase the SSH Timeout) and as I start to use this, I'm sure I have others.

Will changes be accepted or should I fork and move on?

thanks

Brad

**Comment by LordGaav** [comment]
I'm not working actively on proxmox-deploy anymore. However, I will always consider pull requests, especially bugfixes.

On the issue of SSH timeout: since `proxmoxer` uses OpenSSH directly, couldn't you just change the SSH timeout in your client config? It should be picked up by proxmox-deploy then.
